
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-controlplane
  failurePolicy: Fail
  name: vcontrolplane.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - controlplanes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackbaremetalset
  failurePolicy: Fail
  name: vopenstackbaremetalset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackbaremetalsets
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-vmset
  failurePolicy: Fail
  name: vvmset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vmsets
