apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: {{ .BaseImageName }}
  namespace: {{ .Namespace }}
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .DiskSize }}Gi
    volumeMode: Filesystem
{{if .ImageImportStorageClass }}
    storageClassName: {{ .ImageImportStorageClass }}
{{end}}
  source:
    http:
      url: {{ .BaseImageURL }}