apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: {{ .BaseImageVolumeName }}
  namespace: {{ .Namespace }}
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .DiskSize }}Gi
    volumeMode: Filesystem
    storageClassName: {{ .StorageClass }}
  source:
    http:
      url: {{ .BaseImageURL }}
