# permissions for end users to view openstackbaremetalsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackbaremetalset-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbaremetalsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbaremetalsets/status
  verbs:
  - get
