# permissions for end users to edit controllervms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllervm-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - controllervms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - controllervms/status
  verbs:
  - get
