# permissions for end users to view controllervms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllervm-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - controllervms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - controllervms/status
  verbs:
  - get
