# permissions for end users to view overcloudnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overcloudnet-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - overcloudnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - overcloudnets/status
  verbs:
  - get
