# permissions for end users to edit overcloudnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overcloudnet-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - overcloudnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - overcloudnets/status
  verbs:
  - get
