# permissions for end users to edit overcloudipsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overcloudipset-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - overcloudipsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - overcloudipsets/status
  verbs:
  - get
