# permissions for end users to edit vmsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmset-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - vmsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - vmsets/status
  verbs:
  - get
