apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Network }}
  namespace: {{ .Namespace }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/{{ .Network }}
spec:
  config: '{"name":"osp","cniVersion":"0.3.1","plugins":[{"type":"cnv-bridge","bridge":"{{ .Network }}","ipam":{}},{"type":"cnv-tuning"}]}'